# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ghqcr_wrappers", use_symbols = TRUE, package_name = "ghqcr")

#' @usage NULL
#' @useDynLib ghqcr, .registration = TRUE
NULL

setup_configuration_extr <- function(config_dir, git) .Call(wrap__setup_configuration_extr, config_dir, git)

configuration_status_extr <- function(config_dir) .Call(wrap__configuration_status_extr, config_dir)

get_configuration_extr <- function(config_dir) .Call(wrap__get_configuration_extr, config_dir)

get_checklist_display_name_extr <- function(configuration) .Call(wrap__get_checklist_display_name_extr, configuration)

get_prepended_checklist_note_extr <- function(configuration) .Call(wrap__get_prepended_checklist_note_extr, configuration)

get_checklists_extr <- function(configuration) .Call(wrap__get_checklists_extr, configuration)

get_milestones_extr <- function(working_dir) .Call(wrap__get_milestones_extr, working_dir)

get_milestone_issues_extr <- function(working_dir, milestone) .Call(wrap__get_milestone_issues_extr, working_dir, milestone)

get_repo_users_extr <- function(working_dir) .Call(wrap__get_repo_users_extr, working_dir)

create_issues_extr <- function(milestone_name, description, file_data, milestones, prepended_checklist_note, working_dir) .Call(wrap__create_issues_extr, milestone_name, description, file_data, milestones, prepended_checklist_note, working_dir)

file_git_status_extr <- function(files, working_dir) .Call(wrap__file_git_status_extr, files, working_dir)

init_logger_extr <- function() invisible(.Call(wrap__init_logger_extr))

log_message_extr <- function(level, msg) invisible(.Call(wrap__log_message_extr, level, msg))

format_checklist_as_html_extr <- function(checklist_robj) .Call(wrap__format_checklist_as_html_extr, checklist_robj)

read_to_string_extr <- function(path) .Call(wrap__read_to_string_extr, path)

markdown_to_html_extr <- function(content) .Call(wrap__markdown_to_html_extr, content)

get_multiple_milestone_issues_extr <- function(milestones, working_dir) .Call(wrap__get_multiple_milestone_issues_extr, milestones, working_dir)

get_issue_commits_extr <- function(issue, working_dir) .Call(wrap__get_issue_commits_extr, issue, working_dir)

create_qc_comment_extr <- function(issue, filename, from_commit, to_commit, message, show_diff) .Call(wrap__create_qc_comment_extr, issue, filename, from_commit, to_commit, message, show_diff)

get_qc_comment_body_html_extr <- function(qc_comment, working_dir) .Call(wrap__get_qc_comment_body_html_extr, qc_comment, working_dir)

#' Post a QC comment to GitHub
post_qc_comment_extr <- function(qc_comment, working_dir) .Call(wrap__post_qc_comment_extr, qc_comment, working_dir)


# nolint end
