# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ghqcr_wrappers", use_symbols = TRUE, package_name = "ghqcr")

#' @usage NULL
#' @useDynLib ghqcr, .registration = TRUE
NULL

setup_configuration_extr <- function(config_dir, git) .Call(wrap__setup_configuration_extr, config_dir, git)

configuration_status_extr <- function(config_dir) .Call(wrap__configuration_status_extr, config_dir)

get_checklists_extr <- function(config_dir) .Call(wrap__get_checklists_extr, config_dir)

get_milestones_extr <- function(working_dir) .Call(wrap__get_milestones_extr, working_dir)

get_repo_users_extr <- function(working_dir) .Call(wrap__get_repo_users_extr, working_dir)

init_logger_extr <- function() invisible(.Call(wrap__init_logger_extr))

log_message_extr <- function(level, msg) invisible(.Call(wrap__log_message_extr, level, msg))


# nolint end
